## Project Exploring Ebay Car Sales Data

#### Project goal: data cleaning and analized the incuded used car listings

Dataset size: 50000 rows 

The data Dictionary:

* dateCrawled - When this ad was first crawled. All field-values are taken from this date.
* name - Name of the car.
* seller - Whether the seller is private or a dealer.
* offerType - The type of listing
* price - The price on the ad to sell the car.
* abtest - Whether the listing is included in an A/B test.
* vehicleType - The vehicle Type.
* yearOfRegistration - The year in which which year the car was first registered.
* gearbox - The transmission type.
* powerPS - The power of the car in PS.
* model - The car model name.
* kilometer - How many kilometers the car has driven.
* monthOfRegistration - The month in which which year the car was first registered.
* fuelType - What type of fuel the car uses.
* brand - The brand of the car.
* notRepairedDamage - If the car has a damage which is not yet repaired.
* dateCreated - The date on which the eBay listing was created.
* nrOfPictures - The number of pictures in the ad.
* postalCode - The postal code for the location of the vehicle.
* lastSeenOnline - When the crawler saw this ad last online.

In [300]:
from pprint import pprint as pp
import pandas as pd
import numpy as np

In [301]:
fn="autos.csv"
autos = pd.read_csv(fn,encoding="Latin-1")
autos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
dateCrawled            50000 non-null object
name                   50000 non-null object
seller                 50000 non-null object
offerType              50000 non-null object
price                  50000 non-null object
abtest                 50000 non-null object
vehicleType            44905 non-null object
yearOfRegistration     50000 non-null int64
gearbox                47320 non-null object
powerPS                50000 non-null int64
model                  47242 non-null object
odometer               50000 non-null object
monthOfRegistration    50000 non-null int64
fuelType               45518 non-null object
brand                  50000 non-null object
notRepairedDamage      40171 non-null object
dateCreated            50000 non-null object
nrOfPictures           50000 non-null int64
postalCode             50000 non-null int64
lastSeen               50000 non-null object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB

In [302]:
#this shows 25 first and 25 last rows in a nice format
autos

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [303]:
autos.head()

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

In [304]:
autos.columns

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

#### Clean column names

Define a function `clean_col(str)` to apply various string transformation for each column in the list of columns

define a function `camel_to-snake(text)` to perform format transformation based on regular expressions

In [305]:
def camel_to_snake(text):
    import re
    str1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', text)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', str1).lower()

def clean_col(col):
    col = col.strip()
    col = col.replace("yearOfRegistration", "registration_year")
    col = col.replace("monthOfRegistration", "registration_month")
    col = col.replace("notRepairedDamage", "unrepaired_damage")
    col = col.replace("dateCreated", "ad_created")
    col = camel_to_snake(col)
    return col

autos.columns = [ clean_col(c) for c in autos.columns ]

pp(autos.columns)

Index(['date_crawled', 'name', 'seller', 'offer_type', 'price', 'abtest',
       'vehicle_type', 'registration_year', 'gearbox', 'power_ps', 'model',
       'odometer', 'registration_month', 'fuel_type', 'brand',
       'unrepaired_damage', 'ad_created', 'nr_of_pictures', 'postal_code',
       'last_seen'],
      dtype='object')

#### initial data exploration

based on the cell below and from autos.head()
* nr_of_pictures can be dropped
* price and odometor is numeric values stored as text
* features with  nulls  vehicle_type, gearbox, fuel_type, unrepaired_damage

In [306]:
pp( autos.describe() )
#based on output nr_of_pictures can be dropped

#checking for nans
pp(autos.isnull().sum() )

       registration_year      power_ps  registration_month  nr_of_pictures  \
count       50000.000000  50000.000000        50000.000000         50000.0
mean         2005.073280    116.355920            5.723360             0.0
std           105.712813    209.216627            3.711984             0.0
min          1000.000000      0.000000            0.000000             0.0
25%          1999.000000     70.000000            3.000000             0.0
50%          2003.000000    105.000000            6.000000             0.0
75%          2008.000000    150.000000            9.000000             0.0
max          9999.000000  17700.000000           12.000000             0.0

        postal_code
count  50000.000000
mean   50813.627300
std    25779.747957
min     1067.000000
25%    30451.000000
50%    49577.000000
75%    71540.000000
max    99998.000000
date_crawled             0
name                     0
seller                   0
offer_type               0
price                    0
abtest                   0
vehicle_type          5095
registration_year        0
gearbox               2680
power_ps                 0
model                 2758
odometer                 0
registration_month       0
fuel_type             4482
brand                    0
unrepaired_damage     9829
ad_created               0
nr_of_pictures           0
postal_code              0
last_seen                0
dtype: int64

##### checking each categorical variable valuee

In [307]:
autos.date_crawled.value_counts(dropna=False) # strongly diversifed
autos.name.value_counts(dropna=False) #strongly diversified
autos.seller.value_counts(dropna=False) #not diversifed candidate for dropping    !!!
autos.offer_type.value_counts(dropna=False) #not diversifed candidate for dropping !!!!
autos.abtest.value_counts(dropna=False) # 2-categories balanced
autos.vehicle_type.value_counts(dropna=False) # categorical balanced
autos.gearbox.value_counts(dropna=False) #categorical has 4  % of NAs
autos.model.value_counts(dropna=False) #categorical balanced
autos.fuel_type.value_counts(dropna=False) #categorical has 4% of nas
autos.brand.value_counts(dropna=False) #categorical balanced
autos.unrepaired_damage.value_counts(dropna=False) # 2categories, 20% nans
autos.ad_created.value_counts(dropna=False)  #categorical  balanced
autos.last_seen.value_counts(dropna=False) #categorical balanced

2016-04-07 06:17:27    8
2016-04-07 03:16:17    7
2016-04-06 21:17:51    7
2016-04-06 06:17:24    7
2016-04-07 05:16:17    6
2016-04-06 19:15:21    6
2016-04-06 15:17:56    6
2016-04-06 02:16:12    6
2016-04-05 16:44:47    6
2016-04-06 14:17:04    6
2016-04-06 07:46:03    6
2016-04-07 04:46:51    6
2016-04-07 03:45:23    6
2016-04-06 01:16:01    6
2016-04-06 10:17:12    6
2016-04-06 08:44:19    6
2016-04-06 15:16:45    6
2016-04-06 19:16:38    6
2016-04-06 07:46:11    6
2016-04-07 06:46:12    6
2016-04-06 14:44:55    6
2016-04-06 15:45:50    6
2016-04-06 20:48:27    6
2016-04-06 05:16:14    6
2016-04-06 22:17:26    6
2016-04-06 13:17:03    6
2016-04-06 02:17:26    6
2016-04-06 10:45:24    5
2016-04-06 22:45:50    5
2016-04-07 09:45:39    5
                      ..
2016-03-22 11:55:13    1
2016-03-31 00:46:06    1
2016-04-01 16:15:25    1
2016-04-06 21:45:27    1
2016-04-02 02:46:12    1
2016-04-06 17:45:41    1
2016-04-05 12:50:38    1
2016-04-05 07:53:54    1
2016-04-05 18:25:24    1
2016-03-24 01:15:19    1
2016-04-05 19:15:38    1
2016-04-06 12:16:56    1
2016-04-06 01:48:34    1
2016-03-28 06:46:33    1
2016-03-18 11:47:49    1
2016-03-24 06:16:56    1
2016-03-11 11:50:53    1
2016-03-17 23:45:30    1
2016-03-24 17:44:19    1
2016-03-26 22:40:56    1
2016-04-01 18:46:47    1
2016-03-16 08:16:01    1
2016-03-28 09:48:31    1
2016-03-25 10:17:41    1
2016-03-17 13:17:39    1
2016-03-25 19:42:46    1
2016-03-23 01:17:51    1
2016-03-10 06:17:45    1
2016-03-31 11:40:56    1
2016-03-21 17:49:04    1
Name: last_seen, Length: 39481, dtype: int64

In [308]:
autos.drop("nr_of_pictures",axis=1, inplace=True) # this column does not contain useful info

In [309]:
# transform text to floats
autos["price"] = autos["price"].str.split('$',expand=True).iloc[:,1].str.replace(',','').astype(float)
autos["odometer"] = autos["odometer"].str.replace("km",'').str.replace(',','').astype(float)
autos.rename(columns={'odometer':'odometer_km'}, inplace=True)

autos[["price","odometer_km"]].describe()

#odometer_km seems to be good,  price has a high outlier

              price    odometer_km
count  5.000000e+04   50000.000000
mean   9.840044e+03  125732.700000
std    4.811044e+05   40042.211706
min    0.000000e+00    5000.000000
25%    1.100000e+03  125000.000000
50%    2.950000e+03  150000.000000
75%    7.200000e+03  150000.000000
max    1.000000e+08  150000.000000

In [310]:
autos.price.max()  # we have a high max probably an outlier.

99999999.0

In [311]:
#lets explore the high end of prices
autos[autos.price > 500000].loc[:,["name", "odometer_km","price" ]]
# we have ferraris which seems to be correct, the rest is false data

,name,odometer_km,price
514,Ford_Focus_Turnier_1.6_16V_Style,125000.0,999999.0
2897,Escort_MK_1_Hundeknochen_zum_umbauen_auf_RS_2000,50000.0,11111111.0
7814,Ferrari_F40,50000.0,1300000.0
11137,suche_maserati_3200_gt_Zustand_unwichtig_laufe...,100000.0,10000000.0
22947,Bmw_530d_zum_ausschlachten,150000.0,1234566.0
24384,Schlachte_Golf_3_gt_tdi,150000.0,11111111.0
27371,Fiat_Punto,150000.0,12345678.0
37585,Volkswagen_Jetta_GT,150000.0,999990.0
39377,Tausche_volvo_v40_gegen_van,150000.0,12345678.0
39705,Tausch_gegen_gleichwertiges,150000.0,99999999.0
42221,Leasinguebernahme,40000.0,27322222.0
43049,2_VW_Busse_T3,150000.0,999999.0
47598,Opel_Vectra_B_1_6i_16V_Facelift_Tuning_Showcar...,150000.0,12345678.0
47634,Ferrari_FXX,5000.0,3890000.0

In [312]:
autos[((autos.price > 500000) & ~(autos.name.str.contains("Ferrari")) )]
#dropping thos values except  for ferraris
autos=autos[~((autos.price > 500000) & ~(autos.name.str.contains("Ferrari")) )] #antimasking

autos.shape #stripped off 12 rows

(49988, 19)

In [313]:
#converting  ad_created and last_seen to datetime
autos.loc[:,"ad_created"] = pd.to_datetime(autos.loc[:,"ad_created"])
autos.loc[:,"last_seen"] = pd.to_datetime(autos.loc[:,"last_seen"])

/Users/zimine/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [314]:
#adding new numeric columns
autos["ad_created_year"] = autos["ad_created"].dt.year
autos["ad_created_month"] = autos["ad_created"].dt.month

/Users/zimine/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/zimine/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [315]:
autos.ad_created_year.value_counts(normalize=True)

2016    0.99988
2015    0.00012
Name: ad_created_year, dtype: float64

In [316]:
autos.ad_created_month.value_counts(normalize=True)
#interestingly most of adds are posted in march by a large margin and april

3     0.837281
4     0.161099
2     0.001260
1     0.000240
12    0.000040
11    0.000020
9     0.000020
8     0.000020
6     0.000020
Name: ad_created_month, dtype: float64

In [317]:
autos.registration_year.describe()
#for registration yer we have some outliers  near min and max

count    49988.000000
mean      2005.075478
std        105.725062
min       1000.000000
25%       1999.000000
50%       2003.000000
75%       2008.000000
max       9999.000000
Name: registration_year, dtype: float64

In [318]:
autos[autos.registration_year < 1920]

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,...,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen,ad_created_year,ad_created_month
3679,2016-04-04 00:36:17,Suche_Auto,privat,Angebot,1.0,test,NaN,1910,NaN,0,...,5000.0,0,NaN,sonstige_autos,NaN,2016-04-04,40239,2016-04-04 07:49:15,2016,4
10556,2016-04-01 06:02:10,UNFAL_Auto,privat,Angebot,450.0,control,NaN,1800,NaN,1800,...,5000.0,2,NaN,mitsubishi,nein,2016-04-01,63322,2016-04-01 09:42:30,2016,4
15898,2016-03-08 10:50:05,Tausch_alles_aus_meinen_Anzeigen_gegen_Auto,privat,Angebot,0.0,test,NaN,1910,NaN,0,...,5000.0,0,NaN,sonstige_autos,NaN,2016-03-08,6108,2016-03-08 17:47:19,2016,3
22316,2016-03-29 16:56:41,VW_Kaefer.__Zwei_zum_Preis_von_einem.,privat,Angebot,1500.0,control,NaN,1000,manuell,0,...,5000.0,0,benzin,volkswagen,NaN,2016-03-29,48324,2016-03-31 10:15:28,2016,3
22659,2016-03-14 08:51:18,Opel_Corsa_B,privat,Angebot,500.0,test,NaN,1910,NaN,0,...,150000.0,0,NaN,opel,NaN,2016-03-14,52393,2016-04-03 07:53:55,2016,3
24511,2016-03-17 19:45:11,Trabant__wartburg__Ostalgie,privat,Angebot,490.0,control,NaN,1111,NaN,0,...,5000.0,0,NaN,trabant,NaN,2016-03-17,16818,2016-04-07 07:17:29,2016,3
28693,2016-03-22 17:48:41,Renault_Twingo,privat,Angebot,599.0,control,kleinwagen,1910,manuell,0,...,5000.0,0,benzin,renault,NaN,2016-03-22,70376,2016-04-06 09:16:59,2016,3
30781,2016-03-25 13:47:46,Opel_Calibra_V6_DTM_Bausatz_1:24,privat,Angebot,30.0,test,NaN,1910,NaN,0,...,100000.0,0,NaN,opel,NaN,2016-03-25,47638,2016-03-26 23:46:29,2016,3
32585,2016-04-02 16:56:39,UNFAL_Auto,privat,Angebot,450.0,control,NaN,1800,NaN,1800,...,5000.0,2,NaN,mitsubishi,nein,2016-04-02,63322,2016-04-04 14:46:21,2016,4
33295,2016-03-12 10:49:42,Ich_verkaufe/suche_fuer_sie_ihr_Auto!!,privat,Angebot,0.0,control,NaN,1910,NaN,0,...,5000.0,0,NaN,sonstige_autos,NaN,2016-03-12,37075,2016-03-19 07:15:34,2016,3
35238,2016-03-26 13:45:20,Suche_Skoda_Fabia____Skoda_Fabia_Combi_mit_Klima,privat,Angebot,0.0,control,NaN,1500,NaN,0,...,5000.0,0,benzin,skoda,NaN,2016-03-26,15517,2016-04-04 00:16:54,2016,3
42181,2016-03-27 19:50:53,SAMSUNG_55Â“_3D_Tv_und_Soundbar_gegen_Auto,privat,Angebot,0.0,test,NaN,1910,NaN,0,...,5000.0,0,NaN,sonstige_autos,NaN,2016-03-27,57080,2016-04-06 01:15:30,2016,3
45157,2016-03-11 22:37:01,Motorhaube,privat,Angebot,15.0,control,NaN,1910,NaN,0,...,5000.0,0,NaN,trabant,NaN,2016-03-11,90491,2016-03-25 11:18:57,2016,3
46213,2016-04-02 13:47:16,Bellier_Vario,privat,Angebot,0.0,test,kleinwagen,1910,NaN,0,...,5000.0,1,andere,sonstige_autos,NaN,2016-04-02,93105,2016-04-04 11:16:30,2016,4
49283,2016-03-15 18:38:53,Citroen_HY,privat,Angebot,7750.0,control,NaN,1001,NaN,0,...,5000.0,0,NaN,citroen,NaN,2016-03-15,66706,2016-04-06 18:47:20,2016,3

In [319]:
#unrealistic rows with high registration_year date
autos[autos.registration_year > 2016]

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,...,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen,ad_created_year,ad_created_month
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,999.0,test,NaN,2017,manuell,90,...,150000.0,4,benzin,volkswagen,nein,2016-03-14,86157,2016-04-07 03:16:21,2016,3
55,2016-03-07 02:47:54,Mercedes_E320_AMG_zu_Tauschen!,privat,Angebot,1.0,test,NaN,2017,automatik,224,...,125000.0,7,benzin,mercedes_benz,nein,2016-03-06,22111,2016-03-08 05:45:44,2016,3
65,2016-04-04 19:30:39,Ford_Fiesta_zum_ausschlachten,privat,Angebot,250.0,control,NaN,2017,manuell,65,...,125000.0,9,benzin,ford,NaN,2016-04-04,65606,2016-04-05 12:22:12,2016,4
68,2016-04-03 17:36:59,Mini_cooper_s_clubman_/vollausstattung_/_Navi/...,privat,Angebot,10990.0,test,NaN,2017,manuell,174,...,100000.0,0,NaN,mini,nein,2016-04-03,83135,2016-04-05 17:26:26,2016,4
84,2016-03-27 19:52:54,Renault_twingo,privat,Angebot,900.0,control,NaN,2018,NaN,60,...,150000.0,0,NaN,renault,NaN,2016-03-27,40589,2016-04-05 18:46:49,2016,3
113,2016-04-03 14:58:29,Golf_4_Anfaenger_auto,privat,Angebot,1200.0,test,NaN,2017,manuell,75,...,150000.0,7,NaN,volkswagen,NaN,2016-04-03,97656,2016-04-05 14:15:48,2016,4
164,2016-03-13 20:39:16,Opel_Meriva__nur_76000_Km__unfallfrei__scheckh...,privat,Angebot,4800.0,control,NaN,2018,manuell,0,...,80000.0,4,benzin,opel,nein,2016-03-13,37627,2016-04-04 16:48:02,2016,3
197,2016-04-05 10:36:24,VW_Polo_9N_an_Bastler,privat,Angebot,888.0,control,NaN,2017,manuell,64,...,20000.0,7,NaN,volkswagen,ja,2016-04-05,58566,2016-04-07 13:16:13,2016,4
253,2016-03-27 13:25:18,Ford_mondeo_Gas_anlage_mit_TÃœV_04.2017,privat,Angebot,2250.0,test,NaN,2017,manuell,0,...,150000.0,8,benzin,ford,nein,2016-03-27,56575,2016-04-05 15:18:34,2016,3
348,2016-03-17 20:58:24,VW_Beetle_1.8Turbo_mit_Vollausstattung_und_seh...,privat,Angebot,3750.0,control,NaN,2017,manuell,150,...,150000.0,7,NaN,volkswagen,nein,2016-03-17,45896,2016-03-24 17:17:50,2016,3
390,2016-03-25 12:59:06,Fiat_Bertone_X_1_9__X_1/9__X19__X_19__X1_9__X_19,privat,Angebot,7750.0,test,NaN,2018,manuell,76,...,150000.0,6,benzin,fiat,nein,2016-03-25,78239,2016-03-28 12:16:50,2016,3
438,2016-03-10 20:36:25,VW_Golf_5_V_1.6_2004_Klima_Tempomat,privat,Angebot,4150.0,test,NaN,2017,manuell,102,...,150000.0,0,benzin,volkswagen,NaN,2016-03-10,49377,2016-03-13 03:16:51,2016,3
453,2016-03-28 13:51:12,Armee_Jeep,privat,Angebot,9800.0,test,NaN,4500,manuell,0,...,5000.0,0,NaN,jeep,NaN,2016-03-28,7545,2016-04-06 17:45:49,2016,3
454,2016-03-25 09:57:03,Ford_Fiesta_Servo_D3_Kat_86Â€_Steuern_65.000_tkm,privat,Angebot,750.0,test,NaN,2017,manuell,50,...,70000.0,0,benzin,ford,NaN,2016-03-25,12207,2016-03-26 19:47:15,2016,3
457,2016-03-15 17:48:39,Mercedes_Benz_W203_C200_Kombi_Kompressor_c_kla...,privat,Angebot,3000.0,control,NaN,2017,manuell,163,...,150000.0,8,NaN,mercedes_benz,NaN,2016-03-15,40627,2016-03-21 16:49:25,2016,3
477,2016-03-31 08:53:34,CitroÃ«n_C4,privat,Angebot,3200.0,control,NaN,2017,manuell,88,...,125000.0,2,NaN,citroen,nein,2016-03-31,12459,2016-03-31 10:41:30,2016,3
545,2016-03-22 18:50:53,Bmw_x5_/__E53,privat,Angebot,4300.0,test,NaN,2017,automatik,184,...,150000.0,7,NaN,bmw,ja,2016-03-22,56410,2016-03-23 17:27:19,2016,3
548,2016-03-10 17:44:57,Peugeot_206_1.9_Hdi_4_Tueren_Tuev_02.17,privat,Angebot,1399.0,control,NaN,2017,manuell,90,...,150000.0,6,NaN,peugeot,nein,2016-03-10,48153,2016-03-11 05:44:18,2016,3
557,2016-03-16 03:36:34,Smart_Fortwo_Passion_MHD,privat,Angebot,4900.0,test,NaN,2017,automatik,71,...,30000.0,4,NaN,smart,nein,2016-03-16,25474,2016-03-29 15:47:46,2016,3
568,2016-03-18 09:48:44,PRIMA_ANFÃ„NGERAUTO_smart_fortwo_cabrio,privat,Angebot,1950.0,control,NaN,2017,automatik,54,...,125000.0,12,NaN,smart,nein,2016-03-18,25821,2016-04-01 23:47:20,2016,3
577,2016-04-03 14:49:09,Volkswagen_Golf_3,privat,Angebot,650.0,test,NaN,2017,manuell,75,...,150000.0,1,benzin,volkswagen,NaN,2016-04-03,91332,2016-04-05 13:47:38,2016,4
582,2016-03-31 11:57:46,V10_TDI_TOUAREG,privat,Angebot,7300.0,control,NaN,2017,automatik,313,...,150000.0,7,NaN,volkswagen,nein,2016-03-31,53844,2016-04-02 07:17:28,2016,3
654,2016-04-01 15:48:34,Ich_verkaufe_meinen_gepflegten_daewoo,privat,Angebot,2000.0,test,NaN,2017,manuell,0,...,100000.0,5,benzin,daewoo,NaN,2016-04-01,10555,2016-04-07 13:50:05,2016,4
740,2016-04-02 19:49:46,Seat_Leon_zu_verkaufen!,privat,Angebot,2400.0,control,NaN,2017,manuell,104,...,150000.0,2,benzin,seat,ja,2016-04-02,44267,2016-04-05 08:55:09,2016,4
754,2016-03-26 13:47:56,Ford_Ka_Kleinwagen_BJ_2008,privat,Angebot,1850.0,control,NaN,2017,NaN,60,...,125000.0,3,benzin,ford,NaN,2016-03-26,42119,2016-03-29 16:16:19,2016,3
758,2016-03-12 18:42:33,Honda_Civic_mit_TÃœV_!!!,privat,Angebot,1200.0,test,NaN,2017,NaN,90,...,150000.0,12,benzin,honda,ja,2016-03-12,44532,2016-03-17 21:44:42,2016,3
765,2016-03-26 11:52:53,BMW_3er_Limousine_mit_1_Jahr_TÃœV!!!!,privat,Angebot,1350.0,control,NaN,2017,manuell,0,...,150000.0,3,benzin,bmw,NaN,2016-03-26,22846,2016-04-06 00:15:26,2016,3
802,2016-03-19 11:37:23,Lada_mit_wenig_km_neuem_Tuev_bj_08,privat,Angebot,2100.0,test,NaN,2018,manuell,0,...,150000.0,0,benzin,lada,NaN,2016-03-19,12621,2016-03-21 15:20:00,2016,3
871,2016-04-04 19:38:38,Citroen_C2_60_PS,privat,Angebot,1450.0,test,NaN,2017,manuell,60,...,150000.0,3,benzin,citroen,ja,2016-04-04,46117,2016-04-04 19:38:38,2016,4
889,2016-03-12 16:52:19,Verkaufe_Opel_Corsa_C_1_2,privat,Angebot,870.0,control,NaN,2017,manuell,75,...,150000.0,10,benzin,opel,NaN,2016-03-12,94164,2016-03-12 16:52:19,2016,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49153,2016-03-12 01:36:59,Corsa_c20xe,privat,Angebot,2500.0,test,NaN,5000,NaN,0,...,5000.0,0,NaN,opel,NaN,2016-03-12,88214,2016-03-12 22:15:17,2016,3
49154,2016-03-24 17:51:22,Auto_mit_TÃœV_bis_September_2017,privat,Angebot,400.0,control,NaN,2017,manuell,60,...,150000.0,7,NaN,seat,NaN,2016-03-24,50374,2016-04-07 11:16:16,2016,3
49178,2016-03-24 19:58:43,Mazda_323_F_TÃœV__neu_2te_Hand_viele_Neuteile,privat,Angebot,1500.0,control,NaN,2018,manuell,98,...,150000.0,6,NaN,mazda,nein,2016-03-24,41334,2016-03-27 16:47:05,2016,3
49185,2016-03-28 11:45:31,Alfa_Romeo_156_Sportwagon_1_8_T_Spark,privat,Angebot,1200.0,control,NaN,2019,manuell,140,...,150000.0,5,benzin,alfa_romeo,nein,2016-03-28,91058,2016-04-06 13:45:56,2016,3
49218,2016-04-01 19:48:06,Ford_Fiesta_1.3_4/5_Tuerer_16_Monate_Tuev,privat,Angebot,2750.0,control,NaN,2018,manuell,60,...,125000.0,4,benzin,ford,nein,2016-04-01,58089,2016-04-05 16:45:21,2016,4
49245,2016-03-26 08:32:30,Audi_A3_1.8T_tausch_moegl.,privat,Angebot,3300.0,control,NaN,2017,manuell,150,...,150000.0,4,NaN,audi,nein,2016-03-26,35075,2016-04-05 21:44:36,2016,3
49259,2016-03-19 18:45:05,Volkswagen_Lupo_TÃœV_06.2017_Klima,privat,Angebot,999.0,test,NaN,2017,manuell,50,...,150000.0,0,benzin,volkswagen,NaN,2016-03-19,10713,2016-04-07 05:45:32,2016,3
49261,2016-03-10 12:51:40,Toyota_aygo,privat,Angebot,2800.0,test,NaN,2017,manuell,0,...,90000.0,6,benzin,toyota,nein,2016-03-10,93055,2016-03-19 19:18:00,2016,3
49262,2016-03-26 18:31:21,Opel_vectra,privat,Angebot,2000.0,test,NaN,2018,NaN,0,...,150000.0,0,NaN,opel,NaN,2016-03-26,65549,2016-04-06 18:19:01,2016,3
49266,2016-03-10 00:54:09,Toyota_Corolla_Verso_7_Sitzer_104.000km_2_2_Di...,privat,Angebot,7699.0,control,NaN,2017,manuell,177,...,125000.0,12,diesel,toyota,nein,2016-03-09,27751,2016-04-05 19:18:39,2016,3
49342,2016-03-09 20:47:01,Audi_80_b4_S_Color_und_BMW_318ti_compact_Tausc...,privat,Angebot,0.0,test,NaN,2017,manuell,90,...,150000.0,10,benzin,audi,ja,2016-03-09,25853,2016-03-11 17:45:36,2016,3
49343,2016-03-12 11:56:55,bmw_320i_touring,privat,Angebot,4400.0,test,NaN,2017,manuell,0,...,150000.0,0,diesel,bmw,NaN,2016-03-12,86695,2016-03-25 09:15:38,2016,3
49347,2016-03-21 20:41:09,Honda_civic_mit_TÃœV_3/2017,privat,Angebot,950.0,control,NaN,2017,manuell,90,...,150000.0,0,NaN,honda,nein,2016-03-21,99439,2016-03-21 20:41:09,2016,3
49354,2016-04-05 10:31:29,Bmw_e39_523i_mit_neuem_Tuev,privat,Angebot,2499.0,control,NaN,2018,manuell,174,...,150000.0,8,NaN,bmw,nein,2016-04-05,65207,2016-04-05 12:27:15,2016,4
49389,2016-03-10 07:54:10,Astra_G_CC,privat,Angebot,950.0,control,NaN,2017,NaN,0,...,150000.0,0,benzin,opel,NaN,2016-03-10,33332,2016-03-25 07:17:25,2016,3
49411,2016-03-28 12:58:19,Renault_twingo_Tuev_neu,privat,Angebot,1550.0,test,NaN,2018,NaN,0,...,100000.0,0,NaN,renault,NaN,2016-03-28,48739,2016-03-28 13:41:18,2016,3
49522,2016-03-14 10:42:08,Mazda_Demio_zu_verkaufen!_RESERVIERT,privat,Angebot,350.0,control,NaN,2017,manuell,72,...,150000.0,12,NaN,mazda,nein,2016-03-14,32791,2016-03-24 17:45:40,2016,3
49557,2016-03-19 18:42:28,E320_T_cdi_avangart,privat,Angebot,6250.0,test,NaN,2017,automatik,205,...,150000.0,3,diesel,mercedes_benz,nein,2016-03-19,13589,2016-04-07 05:17:42,2016,3
49561,2016-03-27 11:25:23,Ford_Galaxy_1_8_TDCI_7_Sitze_Paoramadach_DPF_AHK,privat,Angebot,6500.0,test,NaN,2017,manuell,0,...,150000.0,6,NaN,ford,NaN,2016-03-27,55128,2016-03-30 13:15:32,2016,3
49653,2016-03-25 20:50:13,Top_zustand_privat,privat,Angebot,1050.0,control,NaN,2017,manuell,110,...,150000.0,8,benzin,renault,nein,2016-03-25,34127,2016-03-28 21:19:07,2016,3
49662,2016-03-10 11:54:09,Daihatsu_Coure_122tkm_Tuev_1/17_2.Hand,privat,Angebot,333.0,test,NaN,2017,manuell,0,...,125000.0,0,benzin,daihatsu,NaN,2016-03-10,41751,2016-03-12 16:15:59,2016,3
49689,2016-03-14 15:44:53,VW_GOLF_V_1.9,privat,Angebot,4700.0,control,NaN,2017,manuell,105,...,150000.0,0,diesel,volkswagen,NaN,2016-03-14,22459,2016-03-16 05:45:48,2016,3
49696,2016-03-08 13:36:21,Audi_A3_1_6_Attraction_mit_TÃœV_10/17,privat,Angebot,1250.0,control,NaN,2017,manuell,101,...,150000.0,8,benzin,audi,nein,2016-03-08,26624,2016-03-08 21:17:30,2016,3
49731,2016-03-28 13:40:31,Renault_MEGANE_1.6_16V__neu_ZANHRIEMEN_TOP_ZUS...,privat,Angebot,1700.0,test,NaN,2017,manuell,0,...,150000.0,7,NaN,renault,nein,2016-03-28,34123,2016-03-31 21:44:52,2016,3
49770,2016-03-15 12:54:26,VW_Polo_6n_Tuev_Neu!__1.6_75PS,privat,Angebot,999.0,control,NaN,2018,manuell,75,...,150000.0,12,benzin,volkswagen,nein,2016-03-15,24321,2016-04-06 02:16:02,2016,3
49796,2016-03-09 09:38:38,Opel_corsa_1.4_zu_verkaufen,privat,Angebot,4500.0,test,NaN,2017,manuell,90,...,70000.0,7,benzin,opel,nein,2016-03-09,88433,2016-03-17 20:45:08,2016,3
49841,2016-03-11 15:37:02,Passat_abzugeben.,privat,Angebot,600.0,test,NaN,2017,manuell,101,...,150000.0,7,NaN,volkswagen,NaN,2016-03-11,53804,2016-03-11 16:41:14,2016,3
49880,2016-03-30 08:52:57,E39_528i_an_Bastler,privat,Angebot,0.0,control,NaN,2017,manuell,193,...,150000.0,4,NaN,bmw,ja,2016-03-30,65468,2016-04-07 01:15:27,2016,3
49910,2016-04-03 21:39:15,Schoener_fast_neuer_Opel_Mokka_in_Zell_Mosel_m...,privat,Angebot,22200.0,test,NaN,9000,automatik,140,...,10000.0,3,benzin,opel,NaN,2016-04-03,56856,2016-04-05 22:18:26,2016,4
49935,2016-04-01 21:48:20,Mercedes_A_klasse_angemeldet_mit_Tuef_und_Auto...,privat,Angebot,800.0,test,NaN,2017,automatik,101,...,150000.0,9,NaN,mercedes_benz,nein,2016-04-01,39108,2016-04-01 21:48:20,2016,4

In [320]:
#keeping rows with sensible registration date 
autos = autos[autos.registration_year.between(1920,2016)]
autos.shape

(48009, 21)

#### stats by car brands

In [324]:
autos.brand.value_counts(normalize=True)
# got lots of VW, bmw, opel merced  audi. i.e. we are in germany

volkswagen        0.212148
bmw               0.110042
opel              0.108146
mercedes_benz     0.095378
audi              0.086421
ford              0.069779
renault           0.047345
peugeot           0.029536
fiat              0.025870
seat              0.018184
skoda             0.016039
mazda             0.015143
nissan            0.015101
smart             0.013914
citroen           0.013914
toyota            0.012477
sonstige_autos    0.010831
hyundai           0.009852
volvo             0.009248
mini              0.008644
mitsubishi        0.008144
honda             0.007853
kia               0.007103
alfa_romeo        0.006624
porsche           0.006103
suzuki            0.005916
chevrolet         0.005707
chrysler          0.003666
dacia             0.002562
daihatsu          0.002562
jeep              0.002250
subaru            0.002187
land_rover        0.002041
saab              0.001604
jaguar            0.001583
trabant           0.001541
daewoo            0.001500
rover             0.001354
lancia            0.001083
lada              0.000604
Name: brand, dtype: float64

In [325]:
cols=["brand", "price", "odometer_km", "registration_year"]
brand_stats = autos[cols].groupby("brand").mean()
brand_stats.sort_values(by=["price", "odometer_km"],ascending=False)

#we observe that most expensive cars are porsche, land rover, jaguar, jeep,. 
#then the next koghort is (merced, bmw, audi, mini)
# then we ahve japanese cars

                       price    odometer_km  registration_year
brand
porsche         44553.467577   97457.337884        2001.238908
sonstige_autos  20848.182692   88028.846154        1994.382692
land_rover      19108.091837  118010.204082        2003.826531
jeep            11434.750000  127546.296296        2002.537037
jaguar          11176.197368  120921.052632        2001.236842
mini            10460.012048   88602.409639        2007.848193
audi             9093.650036  129287.780188        2004.070378
mercedes_benz    8485.239572  130856.082114        2001.980345
bmw              8102.536248  132431.383684        2002.933371
chevrolet        6488.981752   99251.824818        2002.416058
skoda            6334.919481  110954.545455        2006.519481
dacia            5915.528455   84268.292683        2010.536585
kia              5789.351906  112434.017595        2006.821114
hyundai          5308.539112  106511.627907        2007.194503
volkswagen       5231.081983  128724.104075        2002.359843
toyota           5115.333890  115709.515860        2004.323873
volvo            4757.108108  138355.855856        2000.425676
nissan           4664.891034  118572.413793        2003.449655
seat             4296.492554  121563.573883        2004.413517
mazda            4010.771664  124745.529574        2002.917469
suzuki           3995.757042  109049.295775        2003.897887
honda            3988.000000  122851.458886        2001.289125
alfa_romeo       3984.855346  131399.371069        2001.528302
subaru           3765.038095  124857.142857        2000.695238
citroen          3699.935629  119580.838323        2004.440120
ford             3652.095224  124068.656716        2002.659701
smart            3542.706587   99595.808383        2005.440120
mitsubishi       3333.800512  126930.946292        2002.281330
lancia           3246.365385  122019.230769        1999.730769
chrysler         3229.443182  133181.818182        2000.732955
saab             3211.649351  144415.584416        1999.662338
peugeot          3039.468265  127136.812412        2003.724260
opel             2877.722458  129224.768875        2002.176425
fiat             2711.801127  116553.945250        2003.062802
lada             2502.896552   85517.241379        1999.000000
renault          2396.206775  128238.011439        2002.864056
trabant          1572.851351   60405.405405        1982.689189
daihatsu         1556.382114  115284.552846        2001.926829
rover            1528.338462  135615.384615        2000.092308
daewoo           1019.861111  122430.555556        2002.486111

### anaysis next steps

In [342]:
brands=["bmw", "audi", "mercedes_benz", "porsche","land_rover", "mini", "opel", "toyota"]
for b in brands:
    print("models to be sold percentage of manufacturer {}".format(b))
    print(autos[autos.brand==b].model.value_counts(normalize=True).head(5))

models to be sold percentage of manufacturer bmw
3er        0.533228
5er        0.230708
1er        0.104146
x_reihe    0.058719
7er        0.025987
Name: model, dtype: float64
models to be sold percentage of manufacturer audi
a4        0.315147
a3        0.208769
a6        0.202790
andere    0.054559
80        0.052068
Name: model, dtype: float64
models to be sold percentage of manufacturer mercedes_benz
c_klasse    0.258101
e_klasse    0.220747
a_klasse    0.122187
andere      0.099685
clk         0.056481
Name: model, dtype: float64
models to be sold percentage of manufacturer porsche
911        0.498258
andere     0.167247
boxster    0.167247
cayenne    0.167247
Name: model, dtype: float64
models to be sold percentage of manufacturer land_rover
freelander           0.319588
defender             0.237113
discovery            0.134021
range_rover_sport    0.123711
range_rover          0.092784
Name: model, dtype: float64
models to be sold percentage of manufacturer mini
cooper     0.661836
one        0.243961
clubman    0.062802
andere     0.031401
Name: model, dtype: float64
models to be sold percentage of manufacturer opel
corsa     0.329922
astra     0.278547
vectra    0.111981
zafira    0.080072
omega     0.038732
Name: model, dtype: float64
models to be sold percentage of manufacturer toyota
yaris      0.218213
andere     0.185567
corolla    0.152921
avensis    0.123711
aygo       0.104811
Name: model, dtype: float64